### PR TITLE
reset highlighted dendrogram

### PR DESCRIPTION
**Pull request by congyu-lu**
## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
doesn't work. click anywhere outside of matrix svg the tooltip dismisses, but dendro highlight is not cancelled

**Comment by xzhou82** [comment]
branch rebased please pull again @congyu-lu

**Comment by siosonel** [comment]
@xzhou82 does the dendogram highlight need to get cancelled for clicks outside of the dendogram? this may be tricky to implement
```js
select('body').on(`click.hierCluster-${plot.id}`, ()=>{
  // if not the dendogram image or a related menu option, then delete clickedChildren + rerender dendogram
  // but how to be sure that a related menu has been clicked?
})
```

**Comment by congyu-lu** [comment]
> @xzhou82 does the dendogram highlight need to get cancelled for clicks outside of the dendogram? this may be tricky to implement
> 
> ```js
> select('body').on(`click.hierCluster-${plot.id}`, ()=>{
>   // if not the dendogram image or a related menu option, then delete clickedChildren + rerender dendogram
>   // but how to be sure that a related menu has been clicked?
> })
> ```


> @xzhou82 does the dendogram highlight need to get cancelled for clicks outside of the dendogram? this may be tricky to implement
> 
> ```js
> select('body').on(`click.hierCluster-${plot.id}`, ()=>{
>   // if not the dendogram image or a related menu option, then delete clickedChildren + rerender dendogram
>   // but how to be sure that a related menu has been clicked?
> })
> ```

@xzhou82 Right now clicking white on dendogram image, or when a data request triggered, will cancel the highlight.  We want to maintain the highlight after zoom in

**Review by xzhou82 — APPROVED** [review]

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
