### PR TITLE
fix: Bug fix that creating mds3 subtrack with long filter name breaks

### PR DESCRIPTION
**Pull request by xzhou82**
## Description

fix bug introduced in https://github.com/stjude/proteinpaint/pull/797
test at http://localhost:3000/?genome=hg38&gene=ENST00000407796&mds3=GDC, click Samples and select Adenomas, subtk can be created without crashing
all mds3 tests pass

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by creilly8 — COMMENTED** [review]
I don't think this has anything to do with this PR. Nevertheless, when changing from lollipops to occurrence, the skewers remained in the subtracks (see screenshot). In the main track, the skewers are removed entirely. 
Screenshot 2023-11-17 at 2 25 25 PM

**Comment by creilly8** [comment]
@xzhou82, I see no other problems except the download issue (fixed in PR #857) and the rendering above. If the rendering isn't an issue or will be fixed at another time, I'll approve.

**Comment by xzhou82** [comment]
thanks that's by design. in numericmode when not too many variants, variants are spread out and stems will be shown. when too many they are not spread out

**Comment by creilly8** [comment]
> thanks that's by design. in numericmode when not too many variants, variants are spread out and stems will be shown. when too many they are not spread out

Sounds good. I'll approve.

**Review by creilly8 — APPROVED** [review]

**Pull request merged**
