### PR TITLE
Scatter 3D axis labels

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Added axis labels and removed legend on reload. Allowed zoom only of Ctrl pressed. Fixed bugs.
I am hoping with this I can move forward to another task, as 3D plots are not a priority and are time consuming.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by karishma-gangwani — APPROVED** [review]
Thanks Airen. Is there a way to not have labels render in 3-d? And we could possibly show the numerical values on the scale? just a thought.

**Comment by airenzp** [comment]
I would have to build/paint the scale manually. It is not as easy as with D3. I would like to have it also, but is really a lot of effort for something we dont use that often. You can always remove a variable and see the scale in the 2D plot.

**Comment by karishma-gangwani** [comment]
> I would have to build/paint the scale manually. It is not as easy as with D3. I would like to have it also, but is really a lot of effort for something we dont use that often. You can always remove a variable and see the scale in the 2D plot.

okay thanks for clarifying that.

**Comment by airenzp** [comment]
@karishma-gangwani I forgot to mention that you can hide the axes and the labels from the controls menu.

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
