### PR TITLE
Scale leftovers

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Added tooltip info for scaleDotTW. Added integration test for scaled dots.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by karishma-gangwani** [comment]
Thanks for the feature @airenzp. So the scale for minimum goes into a negative value and throws an error. I tested on all-pharma. Also, a single step down in the minimum scale from the default number changes the size of the circles drastically big or small.

**Comment by airenzp** [comment]
Thanks for the tests @karishma-gangwani. I validated now that the min and max values are always on a positive range and I fixed the bug causing the size to become out of proportion.

**Comment by karishma-gangwani** [comment]
Thanks @airenzp the divide by on tsne in all-pharma is not working correctly in this branch. It works on master. I used 'Sex' for the divide by in all data. Can you please check?

**Comment by airenzp** [comment]
Should be fixed now Karishma. Thanks for testing this case!

**Review by karishma-gangwani — DISMISSED** [review]

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
