### PR TITLE
Hierarchical clustering controls

### PR DESCRIPTION
**Pull request by siosonel**
## Description

Add control menu, inputs for hierarchical cliustering. Also fixes the recoery of a saved session, to not create another gene expression group.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
CI breaks

**Comment by siosonel** [comment]
@xzhou82 I fixed the issue with last commit

**Comment by robinpaul85** [comment]
Screenshot 2023-08-23 at 4 12 01 PM
Sometimes, I am not able to see the sample dendrogram, but other times when I scroll I can see the dendrogram.

**Review by xzhou82 — APPROVED** [review]

**Comment by xzhou82** [comment]
> Screenshot 2023-08-23 at 4 12 01 PM Sometimes, I am not able to see the sample dendrogram, but other times when I scroll I can see the dendrogram.

we will fix it later

**Pull request merged**
