### PR TITLE
Enable overlaying violin with survival terms

### PR DESCRIPTION
**Pull request by creilly8**
## Description
Closes issue #1991. 

Changes: 
1. If `term.values` is missing, will return the numeric value labeled as the `Exit code [n]` for survival terms. 
2. Enabled broken integration test

Test: 
1. [Age at dx overlayed with efs](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:%7B%22activeTab%22:1%7D,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22agedx%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%22term2%22:%7B%22id%22:%22efs%22%7D%7D%5D%7D)
2. [Example with term.values](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22IHG%22,%22genome%22:%22hg38%22,%22nav%22:%7B%22activeTab%22:1%7D,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22Age%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%22term2%22:%7B%22id%22:%22Event-free%20survival%22%7D%7D%5D%7D)
3. [Violin integration tests](http://localhost:3000/testrun.html?dir=mass&name=violin.integration)

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by karishma-gangwani** [comment]
Thanks for the pr @creilly8 
In termdbtest, can you test this session file. If I switch from violin to barchart I see an error for termLabel.toUpperCase

[violin-survival.txt](https://github.com/user-attachments/files/16872586/violin-survival.txt)

**Comment by gavrielm** [comment]
Is it possible to just add `term.values` to those survival terms that do not have it?

**Comment by congyu-lu** [comment]
> Thanks for the pr @creilly8 In termdbtest, can you test this session file. If I switch from violin to barchart I see an error for termLabel.toUpperCase
> 
> [violin-survival.txt](https://github.com/user-attachments/files/16872586/violin-survival.txt)

I got the same error but I think its in master too so not related to this PR

**Comment by xzhou82** [comment]
plot code should tolerate missing term.values{} for survival term

**Comment by gavrielm** [comment]
`Exit code 0` and `Exit code 1` are ambiguous. Not clear to the user was they refer to.

**Comment by congyu-lu** [comment]
> `Exit code 0` and `Exit code 1` are ambiguous. Not clear to the user was they refer to.

some datasets (for example IHG) have exit code labels defined in their dbs, some don't have that defined (for example PNET). When the dbs don't have the exit code defined we use "Exit code: n", if the exit code labels are added to all dbs, we don't need to do this "Exit code: n" anymore

**Comment by gavrielm** [comment]
I think they need to always be defined. I don't think `0/1` is clear enough to user what is going on. Can verify with the group that is supplying the data.

**Comment by creilly8** [comment]
> Thanks for the pr @creilly8 In termdbtest, can you test this session file. If I switch from violin to barchart I see an error for termLabel.toUpperCase
> 
> [violin-survival.txt](https://github.com/user-attachments/files/16872586/violin-survival.txt)

@karishma-gangwani, I get the same error in master for TermdbTest and other datasets. I can look into in another PR.

**Comment by xzhou82** [comment]
i agree survival term should require exit codes to be defined. let's fix termdbtest and pnet dataset instead of making these changes

**Pull request closed without merging**
