### PR TITLE
Prototype mass boxplot

### PR DESCRIPTION
**Pull request by creilly8**
## Description
Closes issue #2262. In this PR, a new route for box plots calculates the values on the server and reuses `drawBoxPlot` for the rendering. This box plot prototype renders under a new tab within the summary chart. Future PRs are needed to address questions, implement new features, and fully integrate the box plot within mass. The tab is disabled whilst in development. 

Test: 
1. In `client/plots/summary.js`, comment out line 240 and uncomment line 241
2. See static plots from http://localhost:3000/testrun.html?dir=mass&name=boxplot.integration. 

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
looks good. cannot launch boxplot using summary header toggle. use default plot height 60px, and 10px for outlier dot diameter

**Comment by creilly8** [comment]
> looks good. cannot launch boxplot using summary header toggle. use default plot height 60px, and 10px for outlier dot diameter

@xzhou82, The tab is disabled, really not visible, whilst it's in development. I still have questions about how it should work and whatnot. I'd rather not make it visible to users until my questions are answered.

**Review by xzhou82 — DISMISSED** [review]
the adhoc termdb.violin.js may be combined into the new route termdb.boxplot.ts here

**Review by xzhou82 — APPROVED** [review]
default rowspace=5 is enough. lacks a way to customize rowspace. same thing needs to be fixed for violin asap

**Pull request merged**
