### PR TITLE
Misc fixes in single cell plot

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Fixed layout. Supported custom width and height for plots. Hided button instead of disabling it. @congyu-lu and @siosonel could you check this line

`	insertBefore: this.app.opts?.app?.getPlotHolder && this.showDivId //this looks wrong!!!
`
It looks wrong to me.

Fixed error `{"status":400,"error":"invalid genome name"}`
## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by congyu-lu** [comment]
**insertBefore: this.app.opts?.app?.getPlotHolder && this.showDivId //this looks wrong!!!** 

this is not assigning getPlotHolder to insertBefore, but more like:
if(this.app.opts?.app?.getPlotHolder) insertBefore = this.showDivId
else insertBefore = undefined

**Comment by siosonel** [comment]
> insertBefore: this.app.opts?.app?.getPlotHolder && this.showDivId //this looks wrong!!!

Another explanation besides what Congyu said: in JS boolean operations, 
- AND conjuction (`&&`) will return either the first empty/falsy match or the last value in the chained condition
- OR conjuction (`||`) will return the first truthy/non-empty match or the last value

So, `this.app.opts?.app?.getPlotHolder && this.showDivId` will return empty if opts.app.getPlotHolder does not exist (first empty value) o `showDivId` (last value).

**Comment by airenzp** [comment]
Thanks for the clarification, I was not aware of this

**Comment by xzhou82** [comment]
set gene table to auto width but not to always take full window width
on selecting a cluster from dropdown, disable dropdown and indicate `loading...`
only show gsea button when gene list is successfully retrieved

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
