### PR TITLE
Added scatter menu option to mass UI  if supported by the dataset

### PR DESCRIPTION
**Pull request by airenzp**
Fixes to show option to plot a dynamic scatter fromt the mass scatter button if supported

### CODE REVIEW

**Comment by siosonel** [comment]
Two issues:
1. The y-axis label is mostly hidden
2. The control menu does not show pills for the x, y terms.

Screenshot 2023-06-29 at 2 25 24 PM

Screenshot 2023-06-29 at 2 27 47 PM

**Comment by airenzp** [comment]
Thanks for testing. Should be fixed now

**Comment by siosonel** [comment]
@xzhou82 @airenzp Should this open a summary plot with the tab set to Scatter, and not directly open a sampleScatter plot? For a user who is used to seeing the barchart/violin/scatter tabs in the summary plot, or who has experienced easily switching an overlay term from numeric to categorical, it may seem restrictive and confusing to not have the option to do something similar within this `Dynamic scatter` sandbox.

**Review by siosonel — APPROVED** [review]

**Comment by airenzp** [comment]
Maybe it would be nice to open it in the summary view, I am not sure. It would allow the user to switch between plots etc.

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
