### PR TITLE
Fixed precision in DE table, delete DE table when DE parameters change

### PR DESCRIPTION
**Pull request by robinpaul85**
## Description
Fixed precision in DE table, delete DE table when DE parameters change

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by karishma-gangwani — COMMENTED** [review]
is it possible to use the scientific notation for the p-values that have large decimal places? @robinpaul85

**Comment by robinpaul85** [comment]
> is it possible to use the scientific notation for the p-values that have large decimal places? @robinpaul85

const a=0.0000000000000000001
a.toPrecision(4) yields  "1.000e-19"
const b=0.1000000000000000001
b.toPrecision(4) yields "0.1000"

**Comment by airenzp** [comment]
Also, better to determine the precision based on the number, that is why I mentioned this morning the method roundValueAuto. If you set it to 4 digits you assume that for any number 4 digits is the precision to use. Is that true for all cases? We could also customize roundValueAuto to return scientific notation if required.

**Comment by airenzp** [comment]
Looking at the table I noticed that the scientific notation is already used by default. See

Screenshot 2024-10-07 at 6 46 18 PM

**Review by xzhou82 — APPROVED** [review]
i noticed for BP geneset gsea now returns all 6K genesets. the backend should be changed to return 1K genesets at max

**Pull request merged**
