### PR TITLE
use localStorage to persist jwt by dataset + route

### PR DESCRIPTION
**Pull request by siosonel**
## Description
... and process in the mayGetAuthHeaders() vocab method

Tested with the usual `npm run test:unit --workspace=server` + testrun.htnl.

Also test by logging into vizcom, then [opening vizcom from a link into a separate browser tab/window](http://survivorship.stjude.cloud/), and then try to download data.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
testing at example.auth.html still shows same err, while it works on master

**Comment by siosonel** [comment]
> testing at example.auth.html still shows same err, while it works on master

@xzhou82 I fixed a few more things in this branch. I also updated the example.auth.html in `sjpp/master` to more closely simulate the expected embedder login/logout logic, please pull. There is now a drop down to select protected datasets and also a `New Tab` button to simulate what happens when opening a new browser tab/window while logged in or not in another window.

**Review by xzhou82 — APPROVED** [review]
thanks a lot it now works on auth.html

**Comment by siosonel** [comment]
@karishma-gangwani Please test the [sample view for MB_meta_analysis](https://proteinpaint.stjude.org/?mass-session-id=5NpEAtNwPCI6NdO&noheader=1), is should be fixed. 

@xzhou82: We can now use the `serverconfig.features.sessionTracking: "jwt-only"` flag to simulate a server process that does not have session data for a previous login.

**Comment by karishma-gangwani** [comment]
thanks @siosonel it works now.

**Review by karishma-gangwani — APPROVED** [review]

**Pull request merged**
