### PR TITLE
Scatter divide by

### PR DESCRIPTION
**Pull request by airenzp**
Supporting divide by from the scatter plot. Updated summary plot to pass divideBy term. Updated server side to return multiple charts. Supported all term types: numeric, categoric or geneVariant.

### CODE REVIEW

**Comment by airenzp** [comment]
I found that the hiding effect I was showing you on the meeting(Clicking on a category hides all the samples with that category) is because I mark the samples with that category as hidden. So is not a bug. And since you thought it made sense I leave it as it is.

**Comment by airenzp** [comment]
The summary scatter also seems to be working as expected, when using mbmeta, that has the metastasis stage as numeric.(PNET does not and that is why I did not see the scatter tab I think)

**Comment by airenzp** [comment]
I need to make the tool icons like zoom or search to work on all the charts. I am marking the PR as draft again.

**Comment by airenzp** [comment]
Added some more fixes. Now the zoom icons work, the category is displayed and there are some styling improvements.

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
