### PR TITLE
Violin fixes

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Restored list samples function. Added ticks/bins input parameter. Added `Use common thickness` parameter.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by airenzp** [comment]
I am wondering if this plot is correct. If so I can fix the tests. Please check.

**Comment by karishma-gangwani** [comment]
> I am wondering if this plot is correct. If so I can fix the tests. Please check.

That doesn't look correct Airen.

**Comment by karishma-gangwani** [comment]
> > I am wondering if this plot is correct. If so I can fix the tests. Please check.
> 
> That doesn't look correct Airen. I need to find an example that Xin is talking about and test it in R once.

**Comment by karishma-gangwani** [comment]
> > > I am wondering if this plot is correct. If so I can fix the tests. Please check.
> > 
> > 
> > That doesn't look correct Airen. I need to find an example that Xin is talking about and test it in R once.

In this check that you're performing, I think we shouldn't check the bins but the values themselves before they go into the bins. That's where we can exclude the values from passing into the binbuilder if they're the same in 'plot.values'.

**Comment by airenzp** [comment]
Yeah I noticed the bin object is not an array of numbers, and moved the check to the plot values. It looks like this now

Screenshot 2024-01-23 at 10 23 47 AM

**Comment by karishma-gangwani** [comment]
thanks @airenzp that works but do you think we should move that logic to violin.bins.js because that is a shared file and bins are going to be created there and not on the client side for different plot types specifically?

**Comment by airenzp** [comment]
> thanks @airenzp that works and looks more correct but do you think we should move that logic to violin.bins.js because that is a shared file and bins are going to be created there and not on the client side for different plot types specifically?

Good idea. Done

**Review by karishma-gangwani — APPROVED** [review]
thank you! it works.

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
