### PR TITLE
Init routes

### PR DESCRIPTION
**Pull request by siosonel**
## Description

This PR:
- moves most of the route API definition from server/routes to shared/types/src/routes
- makes route and type def names more consistent
- restores the autogeneration of server route documentation and browser testing (command line testing will be restored in a separate PR)

To test:
- http://localhost:3000/testrun.html?name=*.unit
- `cd client && npm run test:integration && npm run tsc`
- `cd ../server && npx tsc`
- `cd ../shared/types && npx tsc`
- `cd sjpp/proteinpaint && npm run doc`, then restart `npm run dev`, and http://localhost:3000/server.html should load routes

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by karishma-gangwani** [comment]
Thanks @siosonel 

I see the validation for brainImaging showing this error in the response:

`Unexpected token 'S', "Sample bra"... is not valid JSON`

**Comment by karishma-gangwani** [comment]
> Thanks @siosonel. all the tests pass.
> 
> I see the validation for brainImaging showing this error in the response:
> 
> `Unexpected token 'S', "Sample bra"... is not valid JSON`

**Comment by karishma-gangwani** [comment]
I also see the 'top variably expressed genes' option failing in this branch. try with [ash](http://localhost:3000/?noheader=1&massnative=hg38,ASH) dataset under gene expression tab.

**Comment by siosonel** [comment]
> I also see the 'top variably expressed genes' option failing in this branch. try with [ash](http://localhost:3000/?noheader=1&massnative=hg38,ASH) dataset under gene expression tab.

should be fixed now

**Review by karishma-gangwani — APPROVED** [review]

**Review by karishma-gangwani — APPROVED** [review]

**Pull request merged**
