### PR TITLE
gdc bam slicing ui fixes: case by cohort, and more tests

### LINKED ISSUE #1214: gdc bam slicing: cohort filter should limit cases, not bam files
when cohort filter has experimental_strategy=Methylation Array, when such filter is used in /files/ query it returns 0 bam file due to conflicting criteria

https://gdc-ctds.atlassian.net/browse/SV-2384
https://gdc-ctds.atlassian.net/browse/SV-2375

### PR DESCRIPTION
**Pull request by xzhou82**
## Description

closes #1214 
non-CI tests now covers most of cases http://localhost:3000/testrun.html?dir=src&name=block.tk.bam.gdc

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by karishma-gangwani — COMMENTED** [review]
I see some tests failing for matrix.

```
ReferenceError: sleep is not defined
    at TermdbVocab.matrix.Inner.app.vocabApi.getAnnotatedSampleData (http://localhost:49499/bundle.js:6569:4)
    at Matrix.setData (http://localhost:49499/bin/webpack:/testrunproteinpaint/plots/matrix.data.js:148:39)
    at Matrix.main (http://localhost:49499/bin/webpack:/testrunproteinpaint/plots/matrix.js:167:24)
    at Object.update (http://localhost:49499/bundle.js:34183:26)
    at notifyComponents (http://localhost:49499/bundle.js:34375:29)
    at Object.update (http://localhost:49499/bundle.js:34192:13)
    at async Promise.all (index 1)
not ok 275 avoid race condition timed out after 1000ms
```

**Comment by karishma-gangwani** [comment]
> was it this one? http://localhost:3000/testrun.html?dir=mass&name=matrix.integration
> 
> i sometimes get 2 failing tests on master. must be flaky tests. also this branch will not affect matrix

yes the matrix integration. ok I'll approve it.

**Review by karishma-gangwani — APPROVED** [review]

**Comment by xzhou82** [comment]
but sleep is imported in mass/test/matrix.integration.spec.js, so it shouldn't break the way you showed

   4 const { sleep } = require('../../test/test.helpers.js')

to get to the bottom of this, which test were you referring to?

**Comment by siosonel** [comment]
@xzhou82 I added that `const {sleep} = ...` line this morning, so maybe your branch was not based off that master commit and that test would've have failed in your branch.

**Comment by xzhou82** [comment]
ok that's what Karishma saw. please see if the newly added matrix CI are flaky

**Pull request merged**
