### PR TITLE
Plotting violin with kde

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Using kde to plot violin and cleanup. Please check. From the controls the ticks and the bandwidth can be modified. I used this [code](https://observablehq.com/@d3/kernel-density-estimation) as a reference. I also increased the default plot thickness for single plots to increase resolution

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by karishma-gangwani** [comment]
Does the log scale look off to you?

**Comment by xzhou82** [comment]
crazy height for single v plot
restrict auto-determined height within 30 to 130 px

**Comment by airenzp** [comment]
> crazy height for single v plot restrict auto-determined height within 30 to 130 px

Please check now how it looks

**Comment by airenzp** [comment]
> Does the log scale look off to you?

It looks ok to me, but I am not 100% sure is correct.

**Comment by xzhou82** [comment]
[in this](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22hrtavg%22,%22q%22:{%22mode%22:%22continuous%22}},%22term2%22:{%22id%22:%22racegrp%22}}],%22nav%22:{%22activeTab%22:1}}), the Unknown group has only 0 values and shouldn't show violin at all. can kde handle such?

**Comment by xzhou82** [comment]
[here](http://localhost:3000/?genome=hg38&gene=ENST00000407796&mds3=GDC), click `169 samples` > Age at diagnosis. the chart shows wrong age distribution

**Comment by gavrielm** [comment]
Lots of whitespace [here](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22doxorubicin_5%22,%22q%22:{%22mode%22:%22continuous%22}}}],%22nav%22:{%22activeTab%22:1}}):

image

**Comment by airenzp** [comment]
@gavrielm the space has a meaning with KDE since the distribution represents a probability. [Here](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22racegrp%22},%22term2%22:{%22id%22:%22agedx%22,%22q%22:{%22mode%22:%22continuous%22}}}],%22nav%22:{%22activeTab%22:1}})
for example the plots are thicker. It depends on the data.

**Comment by airenzp** [comment]
The spaces are not added by me, are dependent on the data. [Here](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22racegrp%22},%22term2%22:{%22id%22:%22agedx%22,%22q%22:{%22mode%22:%22continuous%22}}}],%22nav%22:{%22activeTab%22:1}}) for example, it does not happen. I have been thinking how to improve it but is not an easy fix. I can work on it in another PR. Since this one is already big.

**Review by gavrielm — APPROVED** [review]
Works great and looks great!

**Review by karishma-gangwani — APPROVED** [review]
Thanks Airen!!

**Review by xzhou82 — APPROVED** [review]
new plots look great. thanks!

**Pull request merged**
