### PR TITLE
Validated case when the sample has no divideBy value

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Fixes issue stjude/sjpp#203

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by karishma-gangwani — DISMISSED** [review]
are the console.logs supposed to stay at lines 203 and 356?

**Comment by airenzp** [comment]
Removed now

**Comment by xzhou82** [comment]
i've rebased and the scatter CI tests now pass. i think the issue is fixed. @karishma-gangwani could you test again?

**Comment by karishma-gangwani** [comment]
> i've rebased and the scatter CI tests now pass. i think the issue is fixed. @karishma-gangwani could you test again?

yes all the tests pass. And I don't see the undefined chart anymore. Although the download svg still only downloads one of them. I think that can be a separate pr. Thanks @airenzp. We can merge.

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
