### PR TITLE
Extend setTermInput()

### PR DESCRIPTION
**Pull request by gavrielm**
## Description

Closes https://github.com/stjude/proteinpaint/issues/1871

`controls.term1.js`, `controls.overlay.js`, and `controls.divide.js` are now merged into `setTermInput()` in `controls.config.js`. `setTermInput()` now handles all term-related controls.

Plot code that was previously using controls.term1/overlay/divide.js (e.g., barchart, violin, cuminc, survival) has been updated to use `setTermInput()`.

Can test by using these plots with overlay and divideBy terms.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by karishma-gangwani** [comment]
I think Airen's pr will have to be merged first.

**Comment by gavrielm** [comment]
> I think Airen's pr will have to be merged first to test this one because running some analyses with custom variables breaks on master.

Ok sounds good

**Comment by siosonel** [comment]
Unrelated issue: a missing chart title in the 1st/left chart causes it to be misaligned with the 2nd/right chart
Screenshot 2024-08-29 at 5.26.38 PM.png
 

Screenshot 2024-08-29 at 5 26 38 PM

**Comment by siosonel** [comment]
Two issues:

1. Should not allow same term for overlay and divide by? or maybe there is a reason to allow that

Screenshot 2024-08-29 at 5 29 46 PM

2. Removing an overlay term causes an intermittent browser error, hard to replicate. I had arrythmias in cuminc, hrtavg overlay, and sex divideBy. Maybe not enough data for the R code to process? I'll see if I run into that error again.

**Comment by gavrielm** [comment]
> Two issues:
> 
> 1. Should not allow same term for overlay and divide by? or maybe there is a reason to allow that
> 
> Screenshot 2024-08-29 at 5 29 46 PM
> 
> 2. Removing an overlay term causes an intermittent browser error, hard to replicate. I had arrythmias in cuminc, hrtavg overlay, and sex divideBy. Maybe not enough data for the R code to process? I'll see if I run into that error again.

For issue 1, we could disable it, but the resulting plot does not seem to be much of an issue:

image

For issue 2, I will also try to replicate it.

**Comment by gavrielm** [comment]
> Unrelated issue: a missing chart title in the 1st/left chart causes it to be misaligned with the 2nd/right chart Screenshot 2024-08-29 at 5.26.38 PM.png
> 
> Screenshot 2024-08-29 at 5 26 38 PM

Should be fixed with new commit

**Review by siosonel — APPROVED** [review]

**Pull request merged**
