### PR TITLE
disable listing samples temp.

### PR DESCRIPTION
**Pull request by karishma-gangwani**
## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by xzhou82 — APPROVED** [review]

**Comment by siosonel** [comment]
@xzhou82 @karishma-gangwani should this have been done in the `sjlife.hg38.js` dataset file, instead of commenting out the code? Also not sure if I need to fix something with auth, if a user is logged into vizcom and the `termdbConfig.displaySampleIds` flag is true, then that option will show up - I assume this is what happened and not that the user was not logged in and was still able to display sample IDs.
```js
   cohort: {
        ...,
	termdb: {
             displaySampleIds: true, // change to false
```

**Comment by karishma-gangwani** [comment]
@siosonel I see. I would think as a user if I am not logged in I shouldn't see that button because it doesn't do anything or if I click the button, it should show me a message to log in to view the samples. since I was logged in for **mbmeta** on prp1, I could see the button but clicking the button didn't load the samples.

**Comment by siosonel** [comment]
@karishma-gangwani Thanks, I now see that confusing mbmeta `List samples` menu option, I only tested with vizcom SJLife after seeing this commit. I work on fixing this.

**Comment by karishma-gangwani** [comment]
thanks @siosonel

**Comment by siosonel** [comment]
@karishma-gangwani Not having the listing is related to this quick fix, since lthe sample ID-name mapping was removed from the barchart response data due to performance issues. So, the code to show the `List sample` needs to be commented as was done here, and reactivated at the same time that the todo (or alternative solution) in the screenshot is done.

Screenshot 2023-10-12 at 4 53 08 PM

**Comment by karishma-gangwani** [comment]
sounds good @siosonel violin also uses that so I can try to work on enabling this.

**Pull request merged**
