### PR TITLE
Refactor module for calling R

### PR DESCRIPTION
**Pull request by gavrielm**
## Description

In this PR, the module for calling `R` in the codebase (`server/src/lines2R.js`) is refactored and renamed as `server/src/run_R.js`.

The `run_R.js` module can now stream a string input into R standard input and return a string output from R standard output. As a result, JSON input can now be stringified and streamed into R.

All instances of `lines2R.js` have been replaced with `run_R.js` in the codebase, except for scripts that are no longer in use (e.g., `mds2.load.vcf.js`, `termdb.phewas.js`, etc.). Code for preparing input/output into `run_R.js` has been updated as well.

Also in the PR, the R code for Wilcox rank sum test has been replaced with Rust code. Rust will need to be recompiled as follows (from pp dir): `cd rust && cargo clean && cargo build --release`

I have already tested all features that use the R module, except for the burden app (@siosonel could you please test this on your end?). For everyone else, please perform additional testing on features that you are familiar with that use R.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by siosonel** [comment]
@gavrielm The burden app works. FYI, I test by loading http://localhost:3000/pcb/#/age-series, or can also test [the server response directly](http://localhost:3000/burden?genome=hg38&dslabel=SJLife&diaggrp=1&sex=1&white=1&agedx=1&bleo=0&etop=0&cisp=0&carbo=0&steriod=0&vcr=0&hdmtx=0&itmt=0&ced=0&dox=0&heart=0&brain=0&abd=0&pelvis=0&chest=0).

**Review by siosonel — APPROVED** [review]
all unit and integration tests pass, and manually tested the [burden route.](http://localhost:3000/burden?genome=hg38&dslabel=SJLife&diaggrp=1&sex=1&white=1&agedx=1&bleo=0&etop=0&cisp=0&carbo=0&steriod=0&vcr=0&hdmtx=0&itmt=0&ced=0&dox=0&heart=0&brain=0&abd=0&pelvis=0&chest=0)

**Review by karishma-gangwani — APPROVED** [review]
violin, gene exp clustering and DE work for me.

**Review by xzhou82 — APPROVED** [review]
thanks a lot

**Pull request merged**
