### PR TITLE
Implement color scale in single cell and scatter plot; code improvements

### PR DESCRIPTION
**Pull request by creilly8**
## Description
Closes issues #2177 and #2178

Changes: 
1. Optional to create a color scale in a svg or g element. It will render on load rather than specifying `.render()`. 
2. Color scale accepts an array of colors and distributes them equally across the color bar. The hic and regression code updated to reflect those changes. 
3. If a callback is provided, clicking on the color scale renders a menu to change the min and max colors. 
4. The color scale is implemented in the mass single cell and scatterplot with the callback. The min value will show zero if the min is greater than zero.
5. Updated color scale unit tests and scatter integration tests

Test, everywhere the color scale is implemented: 
1. [Whole genome hic](http://localhost:3000/?genome=hg19&hicfile=proteinpaint_demo/hg19/hic/hic_demo.hic&enzyme=MboI) -> change the matrix type to log(o/e). The color and scale should update with the plot values.
2. [Hic track](http://localhost:3000/?appcard=Hi-C&example=Hi-C) -> Change the plot color and min cutoff value from the CONFIG menu. Should see the color change and value in the color bar change. 
3. [Regression example](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22regression%22,%22regressionType%22:%22linear%22,%22outcome%22:{%22id%22:%22LV_Ejection_Fraction_3D%22},%22independent%22:[{%22id%22:%22sex%22,%22refGrp%22:%222%22},{%22term%22:{%22type%22:%22snplocus%22},%22q%22:{%22chr%22:%22chr17%22,%22start%22:7664218,%22stop%22:7671018,%22AFcutoff%22:5,%22alleleType%22:0,%22geneticModel%22:0,%22restrictAncestry%22:{%22name%22:%22European%20ancestry%22,%22tvs%22:{%22term%22:{%22id%22:%22genetic_race%22,%22type%22:%22categorical%22,%22name%22:%22Genetically%20defined%20race%22},%22values%22:[{%22key%22:%22European%20Ancestry%22,%22label%22:%22European%20Ancestry%22}]}},%22variant_filter%22:{%22type%22:%22tvslst%22,%22join%22:%22and%22,%22in%22:true,%22lst%22:[{%22type%22:%22tvs%22,%22tvs%22:{%22isnot%22:true,%22values%22:[{%22label%22:%22Bad%22,%22key%22:%22Bad%22}],%22term%22:{%22id%22:%22QC%22,%22name%22:%22Classification%22,%22parent_id%22:null,%22isleaf%22:true,%22type%22:%22categorical%22,%22values%22:{%22Good%22:{%22label%22:%22Good%22,%22key%22:%22Good%22},%22Bad%22:{%22label%22:%22Bad%22,%22key%22:%22Bad%22}}}}},{%22type%22:%22tvs%22,%22tvs%22:{%22ranges%22:[{%22start%22:0.95,%22startinclusive%22:true,%22stopunbounded%22:true}],%22term%22:{%22id%22:%22SJcontrol_CR%22,%22name%22:%22SJLIFE%20control%20call%20rate%22,%22parent_id%22:null,%22isleaf%22:true,%22type%22:%22float%22}}},{%22type%22:%22tvs%22,%22tvs%22:{%22ranges%22:[{%22start%22:0.95,%22startinclusive%22:true,%22stopunbounded%22:true}],%22term%22:{%22id%22:%22CR%22,%22name%22:%22Call%20rate,%20SJLIFE+CCSS%22,%22parent_id%22:null,%22isleaf%22:true,%22type%22:%22float%22}}},{%22type%22:%22tvs%22,%22tvs%22:{%22ranges%22:[{%22start%22:0.95,%22startinclusive%22:true,%22stopunbounded%22:true}],%22term%22:{%22id%22:%22CR_sjlife%22,%22name%22:%22SJLIFE%20call%20rate%22,%22parent_id%22:null,%22isleaf%22:true,%22type%22:%22float%22}}},{%22type%22:%22tvs%22,%22tvs%22:{%22ranges%22:[{%22start%22:0.95,%22startinclusive%22:true,%22stopunbounded%22:true}],%22term%22:{%22id%22:%22CR_ccss%22,%22name%22:%22CCSS%20call%20rate%22,%22parent_id%22:null,%22isleaf%22:true,%22type%22:%22float%22}}},{%22type%22:%22tvs%22,%22tvs%22:{%22isnot%22:true,%22values%22:[{%22label%22:%22yes%22,%22key%22:%221%22}],%22term%22:{%22id%22:%22Polymer_region%22,%22name%22:%22Polymer%20region%22,%22parent_id%22:null,%22isleaf%22:true,%22type%22:%22categorical%22}}}]}}}]}]}) -> Click on rs72829457 in the genome browser. Should see the color menu render with the blue and red colors. 
4. [Single cell example](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22BALL-scrna%22,%22nav%22:{%22header_mode%22:%22only_buttons%22},%22plots%22:[{%22chartType%22:%22singleCellPlot%22,%22sample%22:%22SJBALL030036_D1%22}]}) -> From the gene expression radio button, search for KRAS -> Click on the scale -> Change either the min or max color to see the callback. Also note the min is zero.
5. [Scatter plot example](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22sampleScatter%22,%22name%22:%22Methylome%20TSNE%22,%22colorTW%22:{%22id%22:%22Age%22,%22q%22:{%22mode%22:%22continuous%22}}}]}) -> Click on the scale -> Change either the min or max color to see the callback. Also note the min is zero.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by airenzp** [comment]
Thanks for working on this. Looks great and works great. I am adding some minor fixes/suggestions in this [PR](https://github.com/stjude/proteinpaint/pull/2189). If you approve it will be merged into this branch

**Review by airenzp — APPROVED** [review]

**Review by airenzp — APPROVED** [review]

**Review by xzhou82 — APPROVED** [review]
thanks looks nice. minor thing, should remove spacing between tick line and color stripe

**Comment by xzhou82** [comment]
when the colorscale is clickable, add aria hover label saying `Click to customize colors`

**Comment by airenzp** [comment]
> when the colorscale is clickable, add aria hover label saying `Click to customize colors`

aria-label does not work on svg elements, neither title. We may need to do [this](https://d3-graph-gallery.com/graph/interactivity_tooltip.html)
Also I noticed that from the scatter the edit menu shows here
Screenshot 2024-10-03 at 12 12 45 PM
We may need to pass the event coordinates instead to avoid this shifting

**Pull request merged**
