### PR TITLE
show variable name upon selection in tvs submenu

### PR DESCRIPTION
**Pull request by karishma-gangwani**
## Description

now variable name shows on selection for custom variable

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
how to test?

**Comment by karishma-gangwani** [comment]
> how to test?

If you create groups by selecting variables and click on the blue pill for editing the categories within the variable selected you should see a text showing term.id for that variable in the tvs submenu

**Comment by xzhou82** [comment]
just replace the bold `Select 1 or more` sentense with the variable name

**Comment by karishma-gangwani** [comment]
> just replace the bold `Select 1 or more` sentense with the variable name

okay I made the change. can you test now?

**Comment by xzhou82** [comment]
1. rebase on master
2. confirm if tvs/filter tests all pass
3. revert notify.ts changes if they are accidental

**Comment by karishma-gangwani** [comment]
> 1. rebase on master
> 2. confirm if tvs/filter tests all pass
> 3. revert notify.ts changes if they are accidental

okay. all tests pass.

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
