### PR TITLE
allow to edit axis scale for mds3 numeric mode

### PR DESCRIPTION
**Pull request by xzhou82**
## Description
to test, [open this](http://localhost:3000/?genome=hg38&gene=ENST00000407796&mds3=GDC), click `Variants` and select `As lollipop` this creates a Y axis for the variants. click the "Occurrence" axis label and there is the Y axis editing function.

@gavrielm same applies to p-value scale of snplocus regression block tk axis

@AstridCanal this is prepping for the clinvar AF work, will support INFO fields next!

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by gavrielm** [comment]
Might be useful for the mouse to become a `pointer` when hovering over the y-axis label (similar to the other labels in the margin) so that it is clear that it is clickable.

**Comment by gavrielm** [comment]
When I accidentally set fixed min=40 and max=0 I got this error:

image

Maybe the user should be alerted instead

**Comment by gavrielm** [comment]
After changing fixed scale, there was not a lot padding between top of axis and other labels:

image

Maybe consider increasing the padding

**Comment by xzhou82** [comment]
please test again - now it prevents entering min>max. the padding is calculated differently and is unrelated to scale change

**Review by gavrielm — APPROVED** [review]

**Pull request merged**
