### PR TITLE
matrix: Enable keyboard navigation of menu and control inputs

### PR DESCRIPTION
**Pull request by siosonel**
## Description
Closes https://github.com/stjude/proteinpaint/issues/1123

To test: open matrix and gene expression plots, and 
- try to navigate the controls by pressing Tab
- once the focus is on a matrix/hierCluster control button, press Enter to focus on the menu input under that button
- press Tab to move to the next control or input, press Shift + Tab to move to the previous one
- pressing Enter on a focused button or option should trigger a chart update
- 
NOTES: 
- ~~radio button selection vs focus needs work~~ EDIT: fixed, also clicking on up/down increment on numeric input
- the genesetEdit UI has been updated to handle the display of term group edit/addition (previously worked on @airenzp and used by @congyu-lu in matrix.controls, and may affect may affect screenshots for docs (@karishma-gangwani)

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by congyu-lu — APPROVED** [review]
works great

**Comment by karishma-gangwani** [comment]
thanks @siosonel this 'Display Sample Counts for Gene' option under genes doesn't seem to be doing anything anymore when selected for either of the values. with or without keyboard keys. Is that the intention? 

Display Sample Counts for Gene | Absolute Percent None

and the ENTER keys don't seem to do anything for the SAMPLES tab. 
can anyone check if you see the same.

**Comment by karishma-gangwani** [comment]
another error, probably unrelated, I am seeing is in B-ALL/T-ALL gene exp link when you add one of the MSigDB geneset for example `HALLMARK_TNFA_SIGNALING_VIA_NFKB` throws this error.

image

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at null.get_matrix (webpack://sjcrh/proteinpaint/server/src/termdb.js:354:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at null.<anonymous> (webpack://sjcrh/proteinpaint/server/src/termdb.js:72:34)

**Comment by siosonel** [comment]
> thanks @siosonel
> 
> in the B-ALL/T-ALL link for gene exp clustering this 'Display Sample Counts for Gene' option under genes doesn't seem to be doing anything anymore when selected for either of the values. with or without keyboard keys. Is that the intention?
> 
> Display Sample Counts for Gene | Absolute Percent None
> 
> and the ENTER keys don't seem to do anything for the SAMPLES tab. can anyone check if you see the same.

@karishma-gangwani That option only applies to gene mutations, since for gene expression plots we render only samples with values (so it will always be 100% or equal to total # of available samples). I can hide this input when there are no genes in other panels/term groups, to minimize confusion.

**Comment by karishma-gangwani** [comment]
sorry. another thing. using the keys I was able to go to gene set, Add a new group, and also select a geneset from MSigDB. but I am unable to use the keys after that to press the 'submit' button when the panel shows up with the geneset. When I press ENTER, the chart starts reloading with the previously loaded geneset.

**Comment by siosonel** [comment]
@karishma-gangwani "HALLMARK_TNFA_SIGNALING_VIA_NFKB throws this error" could you open an issue for this? I'll fix in another PR. The error should be handled gracefully, still displayed but should allow the rest of the gene data to be rendered in the matrix/gene expression.

**Comment by karishma-gangwani** [comment]
> @karishma-gangwani "HALLMARK_TNFA_SIGNALING_VIA_NFKB throws this error" could you open an issue for this? I'll fix in another PR. The error should be handled gracefully, still displayed but should allow the rest of the gene data to be rendered in the matrix/gene expression.

done. It's in sjpp repo.

**Comment by siosonel** [comment]
> sorry. another thing. using the keys I was able to go to gene set, Add a new group, and also select a geneset from MSigDB. but I am unable to use the keys after that to press the 'submit' button when the panel shows up with the geneset. I have to use my cursor at this point.

I'll fix this in PR

**Comment by airenzp** [comment]
The UI for adding and editing groups showing the group name on top looks nice and works. The edit button could be named edit groups, as it allows to edit any group, not just the one selected or maybe show the group selected on the button name (Something like Edit **Group A**), as by default one can not see which group is selected until clicking on the edit button.

**Review by karishma-gangwani — APPROVED** [review]

**Review by airenzp — APPROVED** [review]

**Pull request merged**
