### PR TITLE
quick fix to cover term1=geneVariant in barchart CI

### LINKED ISSUE #1061: geneVariant barchart breaks
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22term%22:{%22type%22:%22geneVariant%22,%22name%22:%22TP53%22}}}]}) looking into recent getData() changes

### PR DESCRIPTION
**Pull request by xzhou82**
## Description

closes #1061 
test at http://localhost:3000/testrun.html?dir=mass&name=barchart.integration
waiting on a fix for termdb.barchart.js
must delete `test.only()` before merging

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by siosonel** [comment]
@xzhou82 There are unrelated failing tests, related to summary integration test toggle switching, should be fixed separately. Or let me know and I can try to also fix in this PR.

**Comment by xzhou82** [comment]
thanks geneVariant barchart works. a broken test in http://localhost:3000/testrun.html?dir=mass&name=summary.integration

not ok 6 Render summary plot, term: "agedx" timed out after 6000ms

**Comment by siosonel** [comment]
@xzhou82 should be fixed now

**Comment by xzhou82** [comment]
thanks please merge

**Review by siosonel — APPROVED** [review]

**Pull request merged**
