### PR TITLE
Improved shared/types dev and build scripts

### PR DESCRIPTION
**Pull request by siosonel**
## Description

This update allows consumer code to use type definitions from a published `shared/types` package. Currently in master, only runtime code is assumed to be usable from a published `shared/types` build. The dev workflow has also been streamlined by assuming the use of `tsx` and `esbuild` to not require a full dist build locally. The only additional step required is when consumer code uses typia-generated runtime type checker code,  the developer is expected to rerun from `shared/types` dir either `npm run generate` after changing type definitions, or run `npm run dev` (more expensive due to watch mode).

Run `npm run generate && cp ./checkers/index.js ./dist` from the `shared/types` dir before doing any tests below. 

Tested with
- http://localhost:3000/testrun.html?name=*.unit
- `cd client && npm run test:integration`
- `npm run dev` from sjpp should still work
- editing `shared/types/src/routes` code should trigger server restart
- while running `npm run dev` from `sjpp` dir, temporarily uncomment `validHealthCheckRequest` code (around lines 3, 19-20) in `server/routes/healthcheck.js`, it should trigger a server restart. Run `npm run generate`, it should trigger another server restart. Then open http://localhost:3000/healthcheck?dslabel=1, there should be an error response:
```json
{"status":"error","error":[{"path":"$input.dslabel","expected":"(string | undefined)","value":1}]}
```
- should also be able to run `npm run doc` from `shared/types` dir and open http://localhost:3000/server.html as usual. 

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by karishma-gangwani** [comment]
Thanks @siosonel I see this error:

Am I supposed to run `npm run reset`?

```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/kgangwan/dev/sjpp/proteinpaint/node_modules/@sjcrh/proteinpaint-types/dist/index.js' imported from /Users/kgangwan/dev/sjpp/proteinpaint/server/routes/termdb.topTermsByType.ts
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at d (file:///Users/kgangwan/dev/sjpp/node_modules/tsx/dist/esm/index.mjs:5:34)
    at O (file:///Users/kgangwan/dev/sjpp/node_modules/tsx/dist/esm/index.mjs:5:1162)
    at async nextResolve (node:internal/modules/esm/hooks:865:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:303:24)
    at async handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/kgangwan/dev/sjpp/proteinpaint/node_modules/@sjcrh/proteinpaint-types/dist/index.js'
}
```

**Comment by siosonel** [comment]
> Thanks @siosonel I see this error:
> 
> Am I supposed to run `npm run reset`?
> 
> ```

Please run `npm run generate`, I updated the PR description to include this instruction step.

**Comment by karishma-gangwani** [comment]
> > Thanks @siosonel I see this error:
> > Am I supposed to run `npm run reset`?
> 
> Please run `npm run generate`, I updated the PR description to include this instruction step.

Hmm. I still see the error. I'll wait for others to test and respond. I added @gavrielm to the pr as well.

**Comment by siosonel** [comment]
> > > Thanks @siosonel I see this error:
> > > Am I supposed to run `npm run reset`?
> > 
> > 
> > Please run `npm run generate`, I updated the PR description to include this instruction step.
> 
> Hmm. I still see the error. I'll wait for others to test and respond. I added @gavrielm to the pr as well.

Sorry for the incomplete instructions, run both `npm run generate && cp ./checkers/index.js ./dist` from the `shared/types` dir.

**Comment by karishma-gangwani** [comment]
I see an error in ALL-pharmacotyping ds. Please pull the latest db to test using `node utils/getDataset.js allPharmacotyping`

under 'charts', then 'Drug sensitivity' load  the drug for Asparaginase (normalized). Client side breaks. It works in master.   

```
TypeError: Cannot read properties of undefined (reading 'childType')
    at Object.mayAdjustConfig (summary.js:412:66)
    at TdbStore.plot_create (store.js:272:9)
    at async Object.write (index.js:272:4)
    at async Object.dispatch (index.js:341:30)
```

**Comment by siosonel** [comment]
@karishma-gangwani The error that you saw was [fixed in a separate PR](https://github.com/stjude/proteinpaint/pull/2388) that was just merged to master. I rebased this PR branch to master, and it now works.

**Pull request merged**
