### PR TITLE
Violin condition fix

### PR DESCRIPTION
**Pull request by karishma-gangwani**
Hi @gavrielm and @congyu-lu can you help me test this on sjlife and neuro-onc datasets. Please let me know if you see any issues. I no longer see the toggle issue.

### CODE REVIEW

**Comment by gavrielm** [comment]
What should we be testing?

**Comment by karishma-gangwani** [comment]
> What should we be testing?

when you overlay or use terms that have term.type as a condition. or two numerical terms. if the callbacks on the brushing and label clicking is working correctly or not. 
in general, the violin plot, as it should be functioning.

**Comment by karishma-gangwani** [comment]
> > What should we be testing?
> 
> when you overlay or use terms that have term.type as a condition. or two numerical terms. if the callbacks (hide, filter, list samples) on the brushing and label clicking are working correctly or not. in general, the violin plot, as it should be functioning.

**Comment by congyu-lu** [comment]
> > What should we be testing?
> 
> when you overlay or use terms that have term.type as a condition. or two numerical terms. if the callbacks on the brushing and label clicking is working correctly or not. in general, the violin plot, as it should be functioning.

I guess the brushing -> list samples still doesn't give correct number of samples
Screen Shot 2023-05-17 at 9 28 22 AM

**Comment by gavrielm** [comment]
For this [link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22agedx%22},%22term2%22:{%22id%22:%22agelastvisit%22}}],%22nav%22:{%22activeTab%22:1}}), when switching to `Violin` there is an error

**Comment by gavrielm** [comment]
@congyu-lu I think you need to delete your screenshot as it contains protected information

**Comment by karishma-gangwani** [comment]
> For this [link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22agedx%22%7D,%22term2%22:%7B%22id%22:%22agelastvisit%22%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D), when switching to `Violin` there is an error

@gavrielm can you check now? the latest commit should fix it. 
@congyu-lu the list of samples is correct. You have to brush all the way to the end.

**Comment by gavrielm** [comment]
Thanks, your commit fixed the error. But I also noticed an error with this [link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22BP_SBP1%22,%22q%22:{%22mode%22:%22continuous%22}},%22term2%22:{%22id%22:%22agedx%22}}],%22nav%22:{%22activeTab%22:1}}).

**Comment by karishma-gangwani** [comment]
> Thanks, your commit fixed the error. But I also noticed an error with this [link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22BP_SBP1%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%22term2%22:%7B%22id%22:%22agedx%22%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D).

I see. it was a minor bug on the backend. should be fixed now.

**Review by gavrielm — APPROVED** [review]
Looks good

**Comment by congyu-lu** [comment]
> > For this [link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22agedx%22%7D,%22term2%22:%7B%22id%22:%22agelastvisit%22%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D), when switching to `Violin` there is an error
> 
> @gavrielm can you check now? the latest commit should fix it. @congyu-lu the list of samples is correct. You have to brush all the way to the end.

The brushing->list sample still seems to have issues, The sum of the sample numbers from the two brushes below is less than 56. 
Screen Shot 2023-05-17 at 2 35 35 PM

Screen Shot 2023-05-17 at 2 34 38 PM

**Review by congyu-lu — APPROVED** [review]

**Pull request merged**
