### PR TITLE
Support survival term in cox regression

### PR DESCRIPTION
**Pull request by gavrielm**
## Description

Survival term can now be used as an outcome variable in Cox regression. Regression analysis is now active for datasets with survival terms (e.g., mbmeta, pnet, and ihg) (see [sjpp PR](https://github.com/stjude/sjpp/pull/344)). See [tutorial](https://docs.google.com/document/d/1EyPXH7kdXMiO5WNSVLvOIVE7hMCFPp5uONi29EskRmU/edit#heading=h.2lm0tp6qvrcx) for instructions on setting up a regression analysis.

Here is an example Cox regression analysis in the TermdbTest dataset, using survival as an outcome variabe: http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38-test%22,%22dslabel%22:%22TermdbTest%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22regression%22,%22regressionType%22:%22cox%22,%22outcome%22:{%22id%22:%22os%22},%22independent%22:[{%22id%22:%22sex%22},{%22id%22:%22agedx%22}]}]}

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
thanks the analysis works with termdbtest. please create such a link in url.html in sjpp PR. in future always use termdbtest if it supports the featurre, rather than actual ds; also mbmeta is unpublished and shouldn't be used

**Review by karishma-gangwani — APPROVED** [review]
The analysis works for me.

**Comment by gavrielm** [comment]
> thanks the analysis works with termdbtest. please create such a link in url.html in sjpp PR. in future always use termdbtest if it supports the featurre, rather than actual ds; also mbmeta is unpublished and shouldn't be used

Ok I replaced the mbmeta link with a TermdbTest link in the description and I added the TermdbTest link to url.html

**Review by xzhou82 — APPROVED** [review]
thank you so much; please consider these in next pr

- at cox outcome term summary ui, may show meaningful labels but not 0/1
- if a survival termsetting cannot be edited (for cox), should hide the Edit option
- include survival outcome in regression CI test

**Pull request merged**
