### PR TITLE
Using bootstrap icons for the scatter shapes 

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Improved scatter icons using icons from [here](https://icons.getbootstrap.com/). To resize the icons used the scale transformation instead, as the icons are not built dynamically. Please check.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by karishma-gangwani** [comment]
@airenzp I noticed shapes get suddenly bigger when a category is hidden from the legend. Can you check if that's a bug?

**Review by karishma-gangwani — APPROVED** [review]

**Comment by karishma-gangwani** [comment]
looks good @airenzp Thanks for working on this

**Comment by xzhou82** [comment]
[at view](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22sampleScatter%22,%22name%22:%22Methylome%20TSNE%22,%22colorTW%22:{%22id%22:%22TSNE%20Category%22}}]}), adding `Sample Type` for shape doesn't update

**Comment by karishma-gangwani** [comment]
> [at view](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:%5B%7B%22chartType%22:%22sampleScatter%22,%22name%22:%22Methylome%20TSNE%22,%22colorTW%22:%7B%22id%22:%22TSNE%20Category%22%7D%7D%5D%7D), adding `Sample Type` for shape doesn't update

it works for me. can you pull the branch again and try?

**Pull request merged**
