### PR TITLE
change gdc maf tool to not sort downloaded file based on chr.pos

### PR DESCRIPTION
**Pull request by josephpowi**
## Description

change gdc maf tool to not sort downloaded file based on chr and pos

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by josephpowi** [comment]
can test the script using command:

echo '{"host": "https://api.gdc.cancer.gov/data/", "fileIdLst": ["8b31d6d1-56f7-4aa8-b026-c64bafd531e7", "b429fcc1-2b59-4b4c-a472-fb27758f6249"]}' | ./target/release/gdcmaf

**Comment by xzhou82** [comment]
i don't see it mentioned but please add it no longer sort all lines by chr/pos, but simply concatenate contents of input files (while ensuring lines from different files are not mixed up). thus it won't need to load all lines in memory

i would like @robinpaul85 to review too

how much memory is it taking now for 50Mb compressed input data?

**Comment by josephpowi** [comment]
> i don't see it mentioned but please add it no longer sort all lines by chr/pos, but simply concatenate contents of input files (while ensuring lines from different files are not mixed up). thus it won't need to load all lines in memory
> 
> i would like @robinpaul85 to review too
> 
> how much memory is it taking now for 50Mb compressed input data?

18M

**Comment by xzhou82** [comment]
great. how to measure memory use?

**Comment by josephpowi** [comment]
> great. how to measure memory use?

it was reported by the Activity Monitor. It shows the maximum total amount of memory that the process has allocated is around 18M. I will use memuse crate to test the memory again and will let you know tomorrow.

**Comment by xzhou82** [comment]
great. we will be able to increase mem upper limit

**Comment by josephpowi** [comment]
> great. we will be able to increase mem upper limit

Maybe we can try 2000 samples or even more to see what the memory usage will be like. Probably we don't need to set up the mem limit because it processes and outputs data through the stream.

**Review by robinpaul85 — APPROVED** [review]

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
