### PR TITLE
Matrix group samplecount

### PR DESCRIPTION
**Pull request by siosonel**
## Description

Display sample counts for each legend entry and  in the sample group label plus mouseover. 

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by karishma-gangwani** [comment]
There's some issue with the mouseover. If you add a grouping and mouse over the group label and then mouseover on individual samples the single sample mouseover shows the total samples that are representative of the entire grouping.

**Comment by siosonel** [comment]
@karishma-gangwani Thanks, I have just pushed a commit that fixes the issue that you noted.

**Comment by karishma-gangwani** [comment]
I am seeing this error when I hover over the legend:

`matrix.interactivity.js:1163 Uncaught TypeError: Cannot use 'in' operator to search for 'id' in null
    at self.handleLegendMouseover (matrix.interactivity.js:1163:18)
    at self.showCellInfo (matrix.interactivity.js:15:35)
    at SVGGElement.<anonymous> (on.js:3:14)`

**Comment by siosonel** [comment]
> I am seeing this error when I hover over the legend:

@karishma-gangwani could you `git checkout master; git pull; git branch -D matrix-grp-samplecount; git checkout matrix-grp-samplecount;`? I have pushed a rebased fix for that issue almost immediately after I had pushed earlier

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
