### PR TITLE
Remove the need for a redundant annotations table

### PR DESCRIPTION
**Pull request by siosonel**
The annotations table should be removed after the data prep and db file is created. This will
- decrease the size of the db by removing the redundant annotations table
- remove sql queries from annotations table that require casting, simplifying sql construction and query result processing

TODO: `buildTermdb.js` should have code to delete the annotations table after the db is generated

### CODE REVIEW

**Review by airenzp — DISMISSED** [review]
Looks pretty good to me. You know better than anyone the queries that neeeded to be updated and looked at  that the tests are passing. Do you want me to add the update to buildTermdb about deleting the annotations at the end?

**Comment by siosonel** [comment]
> Looks pretty good to me. You know better than anyone the queries that neeeded to be updated and looked at that the tests are passing. Do you want me to add the update to buildTermdb about deleting the annotations at the end?

@airenzp yes, please update `buildTermdb.js` to remove the annotations table as the end

**Comment by airenzp** [comment]
I just created a PR in sjpp. I thought I could add the line with the drop to the anno-by-type.sql script, at the end.

**Review by xzhou82 — APPROVED** [review]

**Comment by siosonel** [comment]
@xzhou82 or @airenzp: the server init in unit tests have been fixed, please re-approve and merge

**Review by airenzp — APPROVED** [review]

**Pull request merged**
