### PR TITLE
Automatic/Fixed min and max UI in the ColorScale

### PR DESCRIPTION
**Pull request by creilly8**
## Description
Closes issue #2301. @xzhou82, This is a draft PR for feedback whilst PR https://github.com/stjude/proteinpaint/pull/2330 is under consideration. I'd like to finalize all the recent ColorScale changes together in this branch before merging. 

Changes: 
1. UI for switching between `automatic` and `fixed` min and max
2. Callback returns cutoffMode to the caller

Test: 
1. [Color scale unit tests](http://localhost:3000/testrun.html?dir=dom&name=colorScale.unit) -> Use last unit test for both the callbacks
2. [Min and max callback only example](http://localhost:3000/?genome=hg38&gene=bcr&mds3=ASH)
3. [Color callback only example](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22sampleScatter%22,%22name%22:%22Methylome%20TSNE%22,%22colorTW%22:{%22id%22:%22Age%22,%22q%22:{%22mode%22:%22continuous%22}}}]})

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
auto/fixed switching on cnv doesn't work. [test here](http://localhost:3000/?genome=hg38&gene=bcr&mds3=ASH) original auto range is (-3,3), change to fixed, then change back to auto. the range became (-1,1)

**Comment by xzhou82** [comment]
add new tests for ranges e.g. [0.001, 0.005] [-0.005, -0.001]

**Comment by creilly8** [comment]
> add new tests for ranges e.g. [0.001, 0.005] [-0.005, -0.001]

This addressed in [24ab76d](https://github.com/stjude/proteinpaint/pull/2333/commits/24ab76d46d63b878979d08f982a22489fb729428)

**Comment by xzhou82** [comment]
please make sure you [test ash tk and see the cnv legend issue](http://localhost:3000/?genome=hg38&gene=bcr&mds3=ASH)
image

**Review by karishma-gangwani — APPROVED** [review]
looks good to me

**Review by xzhou82 — APPROVED** [review]
ok to merge now but the matrix & disco copy number loss legend is still wrong
[disco](http://localhost:3000/?genome=hg38&dslabel=GDC&disco=1&sample=TCGA-85-7710-01A) loss legend should be from -1 to 0 and blue to white
likewise [matrix](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22ASH%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22matrix%22,%22termgroups%22:[{%22lst%22:[{%22id%22:%22Sex%22},{%22term%22:{%22gene%22:%22TAL1%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22gene%22:%22KRAS%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22gene%22:%22MYB%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22gene%22:%22PAX5%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22gene%22:%22NOTCH1%22,%22type%22:%22geneVariant%22}}]}]}]}) somehow tick labels are scientific notation

**Pull request merged**
