### PR TITLE
updated legend sizes for scatter plot when color and shape variables …

### PR DESCRIPTION
**Pull request by karishma-gangwani**
…are applied

## Description
Hi @airenzp I just enlarged the sizes of the legend icons on the scatter plot. can you test and approve if it looks good? Thanks.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
please set icon size to be the same as text label font size. also [here](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22sampleScatter%22,%22name%22:%22TermdbTest%20TSNE%22,%22colorTW%22:{%22id%22:%22diaggrp%22}}]}) the dot icon appears shifted down

**Comment by airenzp** [comment]
Sorry just saw this now. I feel this change is too drastic. 

Screenshot 2024-10-07 at 9 37 28 PM

**Comment by airenzp** [comment]
> please set icon size to be the same as text label font size. also [here](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:%7B%22activeTab%22:1%7D,%22plots%22:%5B%7B%22chartType%22:%22sampleScatter%22,%22name%22:%22TermdbTest%20TSNE%22,%22colorTW%22:%7B%22id%22:%22diaggrp%22%7D%7D%5D%7D) the dot icon appears shifted down

The icon size is determined by the scale, it is not in the same unit as the font size.

**Comment by airenzp** [comment]
What about using 0.8?

Screenshot 2024-10-07 at 9 43 52 PM

I dont like that the legend shapes are so big in comparison with the real dots, if you really feel this change is needed I would go with 0.8 at the most.

**Comment by karishma-gangwani** [comment]
> What about using 0.8?
> 
> Screenshot 2024-10-07 at 9 43 52 PM
> I dont like that the legend shapes are so big in comparison with the real dots, if you really feel this change is needed I would go with 0.8 at the most.

Thanks @airenzp I believe it was 0.6 earlier so 0.8 is not making a huge difference in the size. What is your suggestion if I want to have those bigger-sized icons? because for shapes 0.6-0.8 becomes small comparitively.

**Review by airenzp — APPROVED** [review]
Improved legend with Karishma and misc fixes

**Comment by xzhou82** [comment]
colortw icon is correctly aligned now but not ref icon
image

**Review by airenzp — APPROVED** [review]

**Comment by xzhou82** [comment]
please make shape icon a little smaller, it should be the same size as color icon

**Pull request merged**
