### PR TITLE
Hic fix

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Closes issue #734 

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
thanks it can get the remote file size now. but on my local the track does not render as hicstat function does not return. is it same for you?

**Comment by airenzp** [comment]
> thanks it can get the remote file size now. but on my local the track does not render as hicstat function does not return. is it same for you?

It does render for me. I wonder what would be different on your end.

**Review by creilly8 — DISMISSED** [review]
This link (http://localhost:3000/?block=1&genome=hg19&position=chr7:13749862-20841903&hictkurl=Test_HiC,MboI,https://proteinpaint.stjude.org/ppdemo/hg19/hic/hic_demo.hic&&hictknorm=VC) worked after 2mins.

**Comment by xzhou82** [comment]
thanks it does render. the /hicstat step takes 90 sec in home wifi. /hicdata takes a few seconds

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
