### PR TITLE
when calculate zscore, should consider valueConversion for numeric an…

### PR DESCRIPTION
**Pull request by congyu-lu**
…d survival

## Description
Test with [this](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22GDC%22,%22genome%22:%22hg38%22,%22nav%22:{%22header_mode%22:%22hidden%22},%22plots%22:[{%22chartType%22:%22matrix%22,%22settings%22:{%22matrix%22:{%22numGenes%22:3}},%22termgroups%22:[{%22lst%22:[{%22term%22:{%22gene%22:%22MYC%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22gene%22:%22HOXA1%22,%22type%22:%22geneVariant%22}},{%22id%22:%22case.diagnoses.age_at_diagnosis%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22Overall%20Survival%22,%22q%22:{%22mode%22:%22continuous%22}}]}]}]})

Convert to z-score should work for Overall survival and Age at diagnosis

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
thanks this allows applying zscore to age term, but i don't think it needs to consider valueConversion, it doesn't matter for zscore

**Comment by congyu-lu** [comment]
> thanks this allows applying zscore to age term, but i don't think it needs to consider valueConversion when it does zscore transformation, it doesn't matter for zscore

valueConversion was considered when calculating values like minval, maxval, label,etc. here we also consider valueConversion to be consistent with those values (otherwise we will get incorrect minval/maxval for scale and incorrect label)

**Review by siosonel — APPROVED** [review]

**Comment by xzhou82** [comment]
has pending fixes

**Comment by congyu-lu** [comment]
> has pending fixes

no more pending fixes, please test again

**Comment by xzhou82** [comment]
mostly works. thanks. minor issues:
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:{%22header_mode%22:%22hidden%22},%22plots%22:[{%22chartType%22:%22matrix%22,%22termgroups%22:[{%22lst%22:[{%22term%22:{%22gene%22:%22TP53%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22gene%22:%22AKT1%22,%22type%22:%22geneVariant%22}},{%22id%22:%22efs%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22agedx%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22diaggrp%22},{%22term%22:{%22gene%22:%22TP53%22,%22type%22:%22geneExpression%22}}]}],%22divideBy%22:{%22id%22:%22sex%22}}]}) convert Age to zscore. hover over cell, the tooltip only shows as `-1(Z-Score)` which lacks a space before `(`; convert gene exp to zscore, in hover tooltip shows as `1 (Z-Score)`. in both cases original value is not shown

**Comment by xzhou82** [comment]
i've changed gdc survival term to decimal years and apply term.unit='year', this works better

**Comment by congyu-lu** [comment]
> mostly works. thanks. minor issues:
> 
> 1. [test link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:%7B%22header_mode%22:%22hidden%22%7D,%22plots%22:%5B%7B%22chartType%22:%22matrix%22,%22termgroups%22:%5B%7B%22lst%22:%5B%7B%22term%22:%7B%22gene%22:%22TP53%22,%22type%22:%22geneVariant%22%7D%7D,%7B%22term%22:%7B%22gene%22:%22AKT1%22,%22type%22:%22geneVariant%22%7D%7D,%7B%22id%22:%22efs%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%7B%22id%22:%22agedx%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%7B%22id%22:%22diaggrp%22%7D,%7B%22term%22:%7B%22gene%22:%22TP53%22,%22type%22:%22geneExpression%22%7D%7D%5D%7D%5D,%22divideBy%22:%7B%22id%22:%22sex%22%7D%7D%5D%7D) convert Age to zscore. hover over cell, the tooltip only shows as `-1(Z-Score)` which lacks a space before `(`; convert gene exp to zscore, in hover tooltip shows as `1 (Z-Score)`. in both cases original value is not shown
> 2. at same link, hover over survival cell the tooltip needs a space before `(years)`

Thanks just fixed these issues

**Comment by xzhou82** [comment]
thanks a lot. last very minor things:
1. no need to show `Z-Score`, just show as `z-score`, in both termsetting ui and cell hover tooltip
2. at [link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:{%22header_mode%22:%22hidden%22},%22plots%22:[{%22chartType%22:%22matrix%22,%22termgroups%22:[{%22lst%22:[{%22term%22:{%22gene%22:%22TP53%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22gene%22:%22AKT1%22,%22type%22:%22geneVariant%22}},{%22id%22:%22efs%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22agedx%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22diaggrp%22},{%22term%22:{%22gene%22:%22TP53%22,%22type%22:%22geneExpression%22}}]}],%22divideBy%22:{%22id%22:%22sex%22}}]}) when hover over age or gene exp cell, the tooltip has no need to show the square of bar color since all bars are same color. when term is zscore can show the blue/red square.
3. suggest to use softer blue/red for zscore bar color

**Comment by congyu-lu** [comment]
> thanks a lot. last very minor things:
> 
> 1. no need to show `Z-Score`, just show as `z-score`, in both termsetting ui and cell hover tooltip
> 2. at [link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:%7B%22header_mode%22:%22hidden%22%7D,%22plots%22:%5B%7B%22chartType%22:%22matrix%22,%22termgroups%22:%5B%7B%22lst%22:%5B%7B%22term%22:%7B%22gene%22:%22TP53%22,%22type%22:%22geneVariant%22%7D%7D,%7B%22term%22:%7B%22gene%22:%22AKT1%22,%22type%22:%22geneVariant%22%7D%7D,%7B%22id%22:%22efs%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%7B%22id%22:%22agedx%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%7B%22id%22:%22diaggrp%22%7D,%7B%22term%22:%7B%22gene%22:%22TP53%22,%22type%22:%22geneExpression%22%7D%7D%5D%7D%5D,%22divideBy%22:%7B%22id%22:%22sex%22%7D%7D%5D%7D) when hover over age or gene exp cell, the tooltip has no need to show the square of bar color since all bars are same color. when term is zscore can show the blue/red square.
> 3. suggest to use softer blue/red for zscore bar color

Thanks just fixed these issues

**Pull request merged**
