### PR TITLE
Improve the matrix sorting options to easily toggle sorting 

### PR DESCRIPTION
**Pull request by siosonel**
## Description

… by cnv and/or consequence.

Screenshot 2024-03-29 at 6 34 51 PM

@congyu-lu Please check this branch in the neuroonc datasets

To test:
1. http://localhost:3000/testrun.html?dir=mass&name=matrix.integration
2. http://localhost:3000/testrun.html?dir=plots&name=matrix.sort.unit
3. GDC:
- Load http://localhost:3000/example.gdc.matrix.html?maxGenes=3&cohort=Gliomas
- `Cases -> Sort by values` should not have a `CNV` checkbox, when the `CNV` button is crossed out
- Click on the CNV button to show all CNV, then the `Cases -> Sort by values : CNV` checkbox should appear in the Cases menu
- Clicking on the `Cases -> Sort by values` CNV and Consequence checkboxes should intuitively re-sort the case columns 

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [ ] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by congyu-lu** [comment]
saw below: is there a sjpp branch associated with this?
image

**Comment by siosonel** [comment]
Yes, I'll push to master later this evening

**Comment by siosonel** [comment]
These are the sorting results with different combinations of hidden CNV + checked sort by values:

Screenshot 2024-03-29 at 11 01 18 PM

Screenshot 2024-03-29 at 10 58 53 PM

**Comment by xzhou82** [comment]
what's the difference between two options of `Sort cases`?
consequence is a terminology specifically used for sequence mutations. CNV gain/loss is not part of "consequence".
menu should be:
SSM: [ ] sort by consequences [ ] sort by presence of mutation
[ ] sort by CNV (future work)

**Comment by siosonel** [comment]
> what's the difference between two options of `Sort cases`? consequence is a terminology specifically used for sequence mutations. CNV gain/loss is not part of "consequence". menu should be: SSM: [ ] sort by consequences [ ] sort by presence of mutation [ ] sort by CNV (future work)

Maybe the first option should be relabeled to `Genomic data`, instead of `Consequence catergory`? Basically, I was trying to find a label that covers both SNVindel, CNV, fusion, any type of such data, in order to avoid having to dynamically change the input label.

Shouldn't sorting by CNV be orthogonal to the sorting by SSM [ consequence OR presense of mutation]? Not sure if those three are inputs arre supposed to be grouped in the same table row, and are they checkboxes or radio buttons?

**Review by congyu-lu — APPROVED** [review]

**Pull request merged**
