### PR TITLE
Tooltip improvement

### PR DESCRIPTION
**Pull request by airenzp**
## Description

PR reusing some ideas from @siosonel  to replace the default tooltip with a nicer one, more visible and responsive. Also added some refactoring. Please check tooltips everywhere and report any issues.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by karishma-gangwani — APPROVED** [review]

**Review by creilly8 — DISMISSED** [review]

**Comment by xzhou82** [comment]
at matrix zoom option, the tooltip at the INPUT now blocks the slider. fine to fix it in next branch (maybe just use slider and no INPUT box)

image

**Comment by airenzp** [comment]
I am ok with it. What do you think about it @xzhou82 ?

**Comment by airenzp** [comment]
I think now looks ok Xin, could you check?

**Review by xzhou82 — APPROVED** [review]
works thanks

**Review by siosonel — APPROVED** [review]

**Pull request merged**
