### PR TITLE
Option to separate multi-valued samples to avoid double counting in the barchart

### PR DESCRIPTION
**Pull request by siosonel**
## Description

Closes https://github.com/stjude/proteinpaint/issues/1005

Work-in progress, 
- more cleanup needed
- fix a failing barchart integration test
- fix the `# of patients` calculation for the chart title: for non-dedup'ed charts, the visibleTotal cannot be assumed to be `[backend computed chart] total - [client-side hidden total]`
- auto-generated dedup series names must not conflict with actual category/group names
 
### New control option

Screenshot 2023-12-16 at 12 33 21 PM

### Groups example

Duplicated, also incorrect chart total (44, not 47) as explained above

Screenshot 2023-12-16 at 12 34 09 PM

vs dedup'ed, correct chart total

Screenshot 2023-12-16 at 12 34 54 PM

### Child condition example

Duplicated

Screenshot 2023-12-16 at 12 32 47 PM

vs deduplicated - should be able to show `# of patients` for condition term in by_child mode

Screenshot 2023-12-16 at 12 32 24 PM

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by airenzp** [comment]
Summarize is looking nice with the deduplicate and coloring sections in the bar (to test it the fix from my PR #1001 needs to be applied). Maybe it would be more intuitive to apply by default the deduplicate, so it is less confusing for the users.

**Comment by gavrielm** [comment]
I get an error when running a barchart of [Subsequent Neoplasms grades](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22Subsequent%20Neoplasms%22}}],%22nav%22:{%22activeTab%22:1}}). Error also happens with barchart of other graded adverse event parent terms (e.g., `Cardiovascular System`)

**Comment by airenzp** [comment]
Thanks for working on this bug so much @siosonel 
A few minor comments, in the message `>1` could be written as more than one, seems more user friendly. Also, it says it would create a third group but this is not reflected on the groups table.
I wanted to try the summarize option, to see if it was reflected then, so I rebased on master. I get this error when trying it 
Screenshot 2023-12-19 at 9 59 32 AM
Let me know if I can help in any way.

**Comment by airenzp** [comment]
Screenshot 2023-12-19 at 10 06 04 AM
These are the groups created.

**Comment by siosonel** [comment]
@airenzp I don't think the message says "third" group, it says a "new" group will be created: 
`A new group will be created for these "overlap" samples"`. In the screenshot example, all the samples in the 2nd group are in the overlap, so that 2nd group is gone.

**Comment by siosonel** [comment]
@airenzp @xzhou82 @gavrielm I've fixed the `propertiees of undefined` issue in Airen's comment above. All integration tests passed locally. I think this is ready to merge.

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
