### PR TITLE
use flags to load charts using runproteinpaint

### PR DESCRIPTION
**Pull request by karishma-gangwani**
## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by xzhou82** [comment]
got err:
launch matrix using runproteinpaint with launchGdcMatrix
index.js:152 error: TypeError: Cannot read properties of null (reading 'style')
    at styleValue (style.js:33:15)
    at 

also please list test sections at the top. see my mds3 test

**Comment by karishma-gangwani** [comment]
> got err: launch matrix using runproteinpaint with launchGdcMatrix index.js:152 error: TypeError: Cannot read properties of null (reading 'style') at styleValue (style.js:33:15) at
> 
> also please list test sections at the top. see my mds3 test

can you check now?

**Review by xzhou82 — APPROVED** [review]

**Comment by xzhou82** [comment]
the branch name sounds angry. name it as issue.1197

**Comment by karishma-gangwani** [comment]
> the branch name sounds angry. name it as issue.1197

I made it specific so it's easier to find it. just naming it with an issue number does not seem specific to me is all. but I can add the issue number to it.

**Pull request merged**
