### PR TITLE
show shape and color in tooltip next to term from shape

### PR DESCRIPTION
**Pull request by karishma-gangwani**
## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [ ] Todos: commented or documented, or N/A
- [ ] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by airenzp** [comment]
My PR makes changes on top of your PR @karishma-gangwani . Both need to be merged. First mine and then yours. I added a comment about it in my PR.

**Comment by karishma-gangwani** [comment]
okay. thanks. Sorry, I missed seeing that since your PR worked fine on master.

**Review by airenzp — APPROVED** [review]

**Comment by airenzp** [comment]
My PR was merged to this PR. If this one is not merged to master, the changes would not be visible in master. I made my PR on top of this one so you could see the changes I suggested to this branch without committing to the branch. This is a common approach when suggesting changes in a PR to avoid committing directly. In this way the person can approve or reject the changes suggested.

**Comment by karishma-gangwani** [comment]
Thanks for explaining @airenzp. Makes sense.

**Pull request merged**
