### PR TITLE
Violin log fix

### PR DESCRIPTION
**Pull request by karishma-gangwani**
@gavrielm this should take care of the sorting with conditional terms and the legend issue with the uncomputable categories. please let me know if you notice anything else. thanks.

### CODE REVIEW

**Comment by gavrielm** [comment]
Thanks for the fixes. For [this link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22cisplatin_5%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%22term2%22:%7B%22id%22:%22Hearing%20loss%22%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D), it is good that the `Not tested` category is hidden by default but I am not able to click it to make it viewable.

**Comment by karishma-gangwani** [comment]
> Thanks for the fixes. For [this link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22cisplatin_5%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%22term2%22:%7B%22id%22:%22Hearing%20loss%22%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D), it is good that the `Not tested` category is hidden by default but I am not able to click it to make it viewable. And if I hide a different category, there appears two different sections of excluded categories:
> 
> image


oh, I see. thanks for catching that. let me check.

**Comment by gavrielm** [comment]
Thanks for the fix. But hidden categories should also be hidden from p-value table:

image

**Review by gavrielm — APPROVED** [review]
Ok sounds good

**Pull request merged**
