### PR TITLE
Used Promise.all to improve plots performance in the PrOFILE

### PR DESCRIPTION
**Pull request by airenzp**
## Description

Used Promise.all to improve plots performance in the PrOFILE. Updated name of file downloaded as requested.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by siosonel** [comment]
@airenzp It seems like using an "empty" chart session file should still help with initial loading, in combination with using `Promise.all()`

**Comment by airenzp** [comment]
I can work on the session idea in another PR, I want to see how much the changes on this PR improve the performance once deployed. Also I will need to do several changes to support the session deployment and I am not so familiar with the session handling, so I prefer to do this in another PR.

**Comment by airenzp** [comment]
For example, when testing the changes we tried yesterday, I was having some issues. See my screenshot
Screenshot 2023-12-12 at 3 40 31 PM
It was including the mass header again, and my function to delete plots was not working. I would need to work on this details.

**Comment by siosonel** [comment]
@airenzp Ok, no problem. It's actually pretty fast loading charts now, I must have used an browser tab with a stale bundled code.

**Review by xzhou82 — APPROVED** [review]

**Pull request merged**
