### PR TITLE
More box plot improvements

### PR DESCRIPTION
**Pull request by creilly8**
## Description
Addresses feedback from previous PR. 

Changes: 
1. Download feature
2. Help icon opens a new wiki page
3. Legend displays the descriptive stats and uncomputable values
4. Hovering over the label displays the individual descriptive stats for each category. 
5. Hovering over the whiskers displays the min and max, respectively. Median appears over the center line. 
6. New controls for width of the entire plot and row space
7. As the number of plots increase, the row height decreases to make space for every plot. The user can still change the plot height and padding in the controls. 
8. More unit and integrations tests. 

Test: 
Add the following to your serverconfig
```
"features" :{
    .....
    "draftChartTypes": [
          "boxplot"
    ]
```
Use any of the examples in http://localhost:3000/url.html. 

Future work: 
1. Showing categorical and conditional terms for the overlay. 
2. Suggested work: 
- Creating draggable divs to reorder the plots
- Adding data points like a swarm or bean plot

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by karishma-gangwani — COMMENTED** [review]
thanks @creilly8 the features mentioned work well. I am seeing some integration tests fail however. Can you check? I am seeing these specifically. 

not ok 422 Should not render tab(s) = Boxplot
not ok 433 Should render 2 tabs: Barchart,Violin for <2 numeric terms
Should render 3 tabs: Barchart,Violin,Scatter for 2 numeric terms

**Comment by creilly8** [comment]
> thanks @creilly8 the features mentioned work well. I am seeing some integration tests fail however. Can you check? I am seeing these specifically.
> 
> not ok 422 Should not render tab(s) = Boxplot not ok 433 Should render 2 tabs: Barchart,Violin for <2 numeric terms Should render 3 tabs: Barchart,Violin,Scatter for 2 numeric terms

I see all the integration tests passing locally in the browser and in github but failing on the command line. The sessionStorage isn't loading to find `draftChartTypes` so this bit of code is causing the issue for the headless browser: 
```
const features = JSON.parse(sessionStorage?.getItem('optionalFeatures')) || {}
const tabLabels2Find = ['Barchart', 'Violin'] //hardcoded data in summary.js.
if (features?.draftChartTypes?.includes('boxplot')) tabLabels2Find.push('Boxplot')
```
I'm not concerned about it since this should be ready for production in few days. I'll remove all the `features?.draftChartTypes` code in the next PR.

**Review by karishma-gangwani — DISMISSED** [review]

**Comment by creilly8** [comment]
@gavrielm. The dictionary issue you noted should be fixed in https://github.com/stjude/proteinpaint/pull/2360/commits/d4012f26021b69917b1090d0d2002ca8086e41b9. Please let me know if you see something different.

**Comment by gavrielm** [comment]
The max when hovering over whisker does not seem to be correct:

image

The value shown seems to be max of all points, the whisker I think represents Q3 + (IQR * 1.5), correct?

**Comment by gavrielm** [comment]
Might also be useful to display Q1 and Q3 on hover if we are doing that for median and whiskers

**Comment by creilly8** [comment]
> ures?.draftChartTypes?.includes('boxpl

Thank you for pointing this out. We'll disable the tooltips.

**Comment by gavrielm** [comment]
Categories in `Other categories` should be crossed off, similar to barchart and violin (to indicate that they are not shown on the plot):

image

**Comment by creilly8** [comment]
> ebc8aa6

Thanks. This is fixed in [ebc8aa6](https://github.com/stjude/proteinpaint/pull/2360/commits/ebc8aa692f89f7912bacf80e7f9872f08310da00).

**Comment by karishma-gangwani** [comment]
I don't see the tooltip on mouseover anymore. can you check @creilly8

**Comment by creilly8** [comment]
> I don't see the tooltip on mouseover anymore. can you check @creilly8

The tooltips are disabled.

**Review by gavrielm — APPROVED** [review]
Thanks works nicely.

Some things to address in next PR:
- Hide/unhide individual boxplots
- Rendering issue when overlay variable has many categories ([example](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22summary%22,%22childType%22:%22boxplot%22,%22term%22:{%22id%22:%22BP_SBP1%22,%22q%22:{%22mode%22:%22continuous%22}},%22term2%22:{%22id%22:%22grade%22}}]}))

**Pull request merged**
