### PR TITLE
Sample view validation if samples returned are empty

### PR DESCRIPTION
**Pull request by airenzp**
## Description

It can be tested adding sampleView to the allowed charts in SJLife and opening it. Before it would cause an error. Now it showns a sign in message.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by siosonel** [comment]
@airenzp The sandbox needs a title, otherwise it's unclear that it's meant for the sample view.

Screenshot 2023-11-01 at 3 10 07 PM

**Review by xzhou82 — APPROVED** [review]

**Comment by siosonel** [comment]
> @airenzp The sandbox needs a title, otherwise it's unclear that it's meant for the sample view.
> 
> Screenshot 2023-11-01 at 3 10 07 PM

@airenzp @xzhou82 I guess we'll wait for customer feedback to get this fixed?

**Comment by xzhou82** [comment]
let's wait to add this view to sjlife, as the mass nav is in the paper figure

**Comment by airenzp** [comment]
Yes we noticed it. I added that fix in this PR https://github.com/stjude/proteinpaint/pull/786.

**Comment by airenzp** [comment]
I meant adding the title in the header. The button itself is only displayed if the plot is added to the allowed ones in the dataset. That is something I do for testing the sampleView, but is not in master.

**Pull request merged**
