### PR TITLE
New styling for variables and categories in regression tooltip

### PR DESCRIPTION
**Pull request by gavrielm**
## Description

Styled the variables and categories in the regression result tooltips as blue pills. View the tooltips by hovering over estimate values (beta, OR, or HR) in the regression results.

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Comment by siosonel** [comment]
When I test with [this url example](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22regression%22,%22regressionType%22:%22linear%22,%22outcome%22:{%22id%22:%22LV_Ejection_Fraction_3D%22},%22independent%22:[{%22id%22:%22agedx%22,%22q%22:{%22mode%22:%22spline%22,%22knots%22:[{%22value%22:1},{%22value%22:4.5},{%22value%22:8.64},{%22value%22:17}]}},{%22id%22:%22diaggrp%22}]}]}), I get empty tooltip over the agedx rows.

Screenshot 2024-11-18 at 5 12 54 PM

**Comment by xzhou82** [comment]
thanks a lot, it needs to deal with this rendering difficulty [link](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22regression%22,%22regressionType%22:%22linear%22,%22outcome%22:{%22id%22:%22LV_Ejection_Fraction_3D%22},%22independent%22:[{%22id%22:%22anthracyclines_jco_5%22,%22q%22:{%22mode%22:%22discrete%22,%22type%22:%22custom-bin%22,%22lst%22:[{%22startunbounded%22:true,%22stopinclusive%22:true,%22stop%22:0,%22label%22:%22Not%20exposed%22},{%22stopinclusive%22:true,%22start%22:0,%22stop%22:100,%22label%22:%22%3E0%20to%20100%22},{%22stopinclusive%22:true,%22start%22:100,%22stop%22:250,%22label%22:%22%3E100%20to%20250%22},{%22startinclusive%22:false,%22stopunbounded%22:true,%22start%22:250,%22label%22:%22%3E250%22}]},%22refGrp%22:%22Not%20exposed%22}]}]})
1. pill can be scaled smaller by style.scale=0.8
2. truncate term name in pill if too long, e.g. at 30 characters

**Comment by gavrielm** [comment]
@siosonel tooltips for cubic spline and genetic terms are not yet supported. These will be supported in the next PR.
@xzhou82 ok I will fix the rendering

**Comment by siosonel** [comment]
> @siosonel tooltips for cubic spline and genetic terms are not yet supported. These will be supported in the next PR. @xzhou82 ok I will fix the rendering

Ok, thanks. Ideally, the tooltip would not be shown for tw term.types or q.modes that are not yet supported.

**Review by siosonel — APPROVED** [review]

**Pull request merged**
