### PR TITLE
prototype a session tracking feature with clearer options

### PR DESCRIPTION
**Pull request by siosonel**
## Description
Also, prefer local cache/file storage, in addition to the option to save in the server or share. ~~This is a draft, will do more integration testing later and include release notes if this approach looks okay to pursue~~.

NOTE: The `Share` option behaves almost the same as the current `Save Session` feature, but notes around expiration may have been lost. Someone else can work on that in another PR, since there is also an open question from @creilly8 on this. 

Test Scenarios for `Open` and `Save`: for each scenario, test that you can save to/open from browser, file, and if applicable, server.

A. Unrpotected ds: comment `serverconfig.dsCredentials.SJLife` (e.g., change to `dsCredentials['#SJLife']`):
  - use [a simple SJLife URL params](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22})
  - there should be no server options in the `Open` and `Save` menus 

B. Protected ds: enable `dsCredentials.SJLife`
  - use http://localhost:3000/example.auth.html
  - there should **be** server options in the `Open` and `Save` menus: I think this matches the requirements in Xin's drawing, but using button + menus instead of tab + tray
  - test while logged in and not
  - when saving to server, you should see the file saved in `[cachedir]/sessionsByCred/...`

C. Same as B, but simulate an embedded use case
  - `sudo vim /etc/hosts` and add the entry `127.0.0.1 viz.localhost`
  - change `dsCredentials['SJLife']` to `dsCredentials['*']` - all embedders will use the same jwt secret
  - from the `sjpp` dir, run `./proteinpaint/server/test/fake-jwt.js SJLife > public/fake-jwt.json '*'`
  - use http://viz.localhost:3000/example.auth.html (different subdomain)
  - manually test like in B
  - Also test that the `Share`-generated URL opens within `viz.localhost`, and not in `localhost`

The goal is to emulate familiar behavior, such as the `File: > open | save | share | ...` options that are very typical in desktop apps.

Screenshot 2023-10-27 at 6 14 49 PM
Screenshot 2023-10-27 at 6 15 42 PM
Screenshot 2023-10-27 at 6 16 02 PM
Screenshot 2023-10-27 at 6 16 19 PM

## Checklist

[Check each task](https://github.com/stjude/proteinpaint/wiki/Pull-Request-Checklist) that has been performed or verified to be not applicable.
- [x] Tests: added and/or passed unit and integration tests, or N/A
- [x] Todos: commented or documented, or N/A
- [x] Notable Changes: updated release.txt, prefixed a commit message with "fix:" or "feat:", added to an internal tracking document, or N/A

### CODE REVIEW

**Review by karishma-gangwani — APPROVED** [review]
Thanks @siosonel. I like you added the share option. I think if this is going to be released then you could replace the TODO with 'feature not enabled yet' or something.

**Comment by xzhou82** [comment]
looks nice. right now it no longer saves on server. i still want an option to save on server, client saving won't work when one person browse portal on multiple devices, and sharing is a hassle

**Comment by xzhou82** [comment]
eventually we will let user see all their saved sessions when they are logged in via viz, from any device.

**Comment by creilly8** [comment]
@siosonel, I uploaded a mass session file from master and worked it great. The download and upload worked well for me too. Unless user feedback suggests another layout, I think this looks great. 

Side note: There's already a share button at the top of every viz in vizcom, albeit very small and in the upper left hand corner. Maybe utilize that? It's probably too much work for too little gain but could be an option later. If anything it would be a good test run for building an API to save to the customer's server rather than our own.

**Comment by creilly8** [comment]
I'm also a big fan of the upload because the exported file downloads to Documents or Desktop.

**Comment by creilly8** [comment]
@xzhou82 Does this mean we will keep session files longer than 30 days (the current limit)? In other words, will this new feature impact how we store session files on the server?

**Comment by siosonel** [comment]
> @xzhou82 Does this mean we will keep session files longer than 30 days (the current limit)? In other words, will this new feature impact how we store session files on the server?

@creilly8 I coded the `Share` feature to behave almost the same as the current `Save Session` feature, so it may still be good to keep track of session storage expirations.

**Review by xzhou82 — APPROVED** [review]
thanks

**Comment by siosonel** [comment]
> @siosonel, I uploaded a mass session file from master and worked it great. The download and upload worked well for me too. Unless user feedback suggests another layout, I think this looks great.
> 
> Side note: There's already a share button at the top of every viz in vizcom, albeit very small and in the upper left hand corner. Maybe utilize that? It's probably too much work for too little gain but could be an option later. If anything it would be a good test run for building an API to save to the customer's server rather than our own.

@creilly8 Using the embedder's share button will be preferred, but yes, it would require some coordination with vizcom so something we could design and plan

**Pull request merged**
